apiVersion: v1
kind: ConfigMap
metadata:
  name: mygoweb
data:
  message.txt: |
    欢迎访问我的应用！
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygoweb
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mygoweb
  template:
    metadata:
      labels:
        app: mygoweb
    spec:
      containers:
        - image: docker.io/library/mygoweb:1.0.1
          name: mygoweb
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /app
      volumes:
      - name: config-volume
        configMap:
          name: mygoweb