apiVersion: v1
kind: Service
metadata:
  name: mygoweb
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: mygoweb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mygoweb-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: mygoweb.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mygoweb
            port:
              number: 80